# Trajopt needs the environment and the costs/constraints
# Env includes models in the environment and robot joint states
sensor_msgs/JointState start
bool plot_traj_steps
bool plot_final_traj
string file_name
---
# Returns a trajectory
tesseract_msgs/Trajectory trajectory
int32 status